Included tritonclient dependency in requirements
triton-inference-server/model_analyzer pull request #115
Opened 2021-04-10 01:11 UTC by aramesh7

2021-04-10 20:04 UTC, Tabrizian requested changes
Can you please fix the setup.py too? The required changes are in the commit below:

https://github.com/triton-inference-server/model_analyzer/pull/26/commits/3448283cebdd07f7b39400abea50a375917842f5

2021-04-12 00:25 UTC, aramesh7 commented
> Can you please fix the setup.py too? The required changes are in the commit below:
> 
> [3448283](https://github.com/triton-inference-server/model_analyzer/commit/3448283cebdd07f7b39400abea50a375917842f5)

I added it but I wonder if its necessary. The nvidia pyindex needs to be installed in order to find the model analyzer pip wheel so i feel like it would be safe to assume it would be present.

2021-04-12 16:55 UTC, Tabrizian commented
I think by default in setup.py it fetches the packages from pypi.

2021-04-12 16:57 UTC, Tabrizian approved these changes

2021-04-12 23:27 UTC, merged