Add option to disable preferred batch size sweep
triton-inference-server/model_analyzer pull request #184
Opened 2021-07-26 22:35 UTC by kthui

2021-07-26 22:41 UTC, kthui commented
There are many styling script updates to `model_analyzer/config/input/config_command_profile.py` file. The real changes are `Line 38, 435 - 441`.

2021-07-27 18:21 UTC, Tabrizian requested changes
Can you add a test for this in `L0_config_search` as well?

2021-07-27 18:24 UTC, kthui commented
Yes. Will work on it.

2021-07-28 21:48 UTC, kthui commented on qa/L0_config_search/test_config_generator.py
> +        self._write_file(4, 2, 4, 1, model_config)
New test case for disabling preferred batch size sweep.

2021-07-29 16:14 UTC, Tabrizian approved these changes

2021-07-29 23:38 UTC, kthui commented
Merged, as the next PR is likely to step on this one.

2021-07-29 23:38 UTC, merged