Now all 'less is better' and 'more is better' tests are being tested
triton-inference-server/model_analyzer pull request #238
Opened 2021-11-09 22:51 UTC by cvinson830

The record types in the model-analyzer.record.types package is contextual when it uses 'less than' and 'greater than' operators.
The 'less than' and 'greater than' operators are overloaded to mean 'worse than' and 'better than' respectively.

- Some record types treat MORE as better (eg, gpu_free_memory, cpu_available_ram)
- Other record types treat LESS as better (eg, gpu_used_memory, cpu_used_ram)

So, when comparing two objects of type cpu_used_ram  12 > 13 is actually true, since 12 'is better than' 13.
Based on this context, the code is working fine.

-------------------------------------------------------------------------------------------------------

However, not all record types were being tested.  
This PR closes the gap so that all record types are tested in two ways:

1. Make sure that the count of 'less is better tests' plus the count of 'more is better tests' equals the total number of tests.
2. Update tests that use 'less is better' and 'more is better' to fail if it's not accounted for

2021-11-10 14:45 UTC, tgerdesnv requested changes
Please add a high level description of the file/class near line 21

2021-11-10 16:37 UTC, cvinson830 commented
> Please add a high level description of the file/class near line 21

Done.

2021-11-10 17:29 UTC, tgerdesnv approved these changes

2021-11-10 17:41 UTC, merged

2021-11-22 16:19 UTC, Tabrizian commented on tests/test_record_types.py
> +                fail
How about using `self.assertTrue(False, 'An error message')` instead of an undefined variable?

2021-11-22 16:19 UTC, Tabrizian commented on tests/test_record_types.py
> +                fail
@cvinson830 Same as below.