WIP: remove preferred batch size
triton-inference-server/model_analyzer pull request #269
Opened 2021-12-14 01:10 UTC by debermudez

2021-12-17 17:02 UTC, tgerdesnv requested changes

2021-12-17 21:09 UTC, debermudez commented on qa/L0_config_search/test_config_generator.py
> +        concurrency_count = len(range(1, concurrency + 1))
Yea. I updated this function to remove some of the complication. It is also commented now.

2021-12-17 21:09 UTC, debermudez commented on qa/L0_cpu/test.sh
> +# dynamic batch size:   1       ->  [1]; now is either on or off
Updated the comment to reflect that it is always on now.

2021-12-17 21:23 UTC, debermudez commented on model_analyzer/reports/report_manager.py
> +            dynamic_batch_phrase = f"dynamic batching unknown"
Added an assertion. The unknown case should not happen so the assertion should guard us against an issue now.

2021-12-17 21:26 UTC, debermudez commented on model_analyzer/config/run/run_search.py
> +        self._model_config_parameters['dynamic_batching'] = None
Good call. Added a comment.

2021-12-17 21:27 UTC, debermudez commented on docs/config_search.md
> +settings, Model Analyzer tries enabling/disabling dynamic batching.
Corrected.

2021-12-17 22:20 UTC, tgerdesnv requested changes

2021-12-17 22:20 UTC, tgerdesnv commented on qa/L0_config_search/test_config_generator.py
> +        Calculate the total number of configs that MA will try
Some more details of the args would be nice:

Given the count of concurrencies and instances to sweep over, calculate and return the total number of parameter combinations that MA will try.  default_config_count indicates how many extra model configs will be run in addition to the normal sweep, and should be set to 0 if the default config is already part of the sweep space.

2021-12-18 00:54 UTC, tgerdesnv approved these changes

2021-12-18 00:54 UTC, merged