add min instance count and concurrency
triton-inference-server/model_analyzer pull request #352
Opened 2022-03-28 23:58 UTC by debermudez

Adding a minimum instance count and minimum concurrency option to MA

2022-03-29 12:31 UTC, tgerdesnv requested changes

2022-03-29 12:31 UTC, tgerdesnv commented on model_analyzer/config/generate/generator_utils.py
> +        return log2_list
endline

2022-03-29 21:26 UTC, debermudez commented on tests/test_perf_analyzer_config_generator.py
> +        3 configs [5, 8, 16] will be generated
Updated per our discussion offline

2022-03-29 21:26 UTC, debermudez commented on model_analyzer/config/generate/generator_utils.py
> +        return log2_list
Done

2022-03-29 21:26 UTC, debermudez commented on model_analyzer/config/generate/generator_utils.py
> +        # min_log_value = 0 if min_value == 0 else int(log2(min_value))
Done

2022-03-30 21:03 UTC, tgerdesnv requested changes

2022-03-30 21:03 UTC, tgerdesnv commented on tests/test_perf_analyzer_config_generator.py
> +        concurrencies = utils.generate_doubled_list(5, 16)
I'd rather this be explicitly called out as [5,10] instead of showing what low level function the code relies on.

2022-03-30 21:03 UTC, tgerdesnv commented on tests/test_perf_analyzer_config_generator.py
> +        3 configs [5, 8, 16] will be generated
comment is incorrect.

2022-03-30 21:05 UTC, debermudez commented on model_analyzer/config/generate/generator_utils.py
> +    def generate_log2_list(min_value, max_value):
Brian asked that we leave it for now.

2022-03-30 21:18 UTC, tgerdesnv approved these changes

2022-03-30 22:39 UTC, merged