Add --gpus flag
triton-inference-server/model_analyzer pull request #38
Opened 2020-11-20 22:48 UTC by Tabrizian

* Adds a `--gpus` flag to control the GPUs being used for analysis.
* Adds checks to make sure that Model Analyzer and Triton are using the same GPUs
* Fixes minor bug if the `start_monitoring_metrics` and `stop_monitoring_metrics` are called without any delay.
```
test_gpu_id (tests.test_dcgm_monitor.TestDCGMMonitor) ... ok
test_immediate_start_stop (tests.test_dcgm_monitor.TestDCGMMonitor) ... ok
test_record_memory (tests.test_dcgm_monitor.TestDCGMMonitor) ... /home/itabrizian/miniconda3/envs/nvml-py/lib/python3.8/multiprocessing/pool.py:265: ResourceWarning: unclosed running multiprocessing pool <multiprocessing.pool.ThreadPool state=RUN pool_size=1>
  _warn(f"unclosed running multiprocessing pool {self!r}",
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_record_utilization (tests.test_dcgm_monitor.TestDCGMMonitor) ... ok
{"total": 4, "errors": 0, "failures": 0}
test_write (tests.test_file_writer.TestFileWriterMethods) ... ok
{"total": 5, "errors": 0, "failures": 0}
test_add_get_methods (tests.test_output_table.TestOutputTableMethods) ... ok
test_create_headers (tests.test_output_table.TestOutputTableMethods) ... ok
test_remove_methods (tests.test_output_table.TestOutputTableMethods) ... ok
test_set_width_methods (tests.test_output_table.TestOutputTableMethods) ... ok
test_to_formatted_string (tests.test_output_table.TestOutputTableMethods) ... ok
{"total": 10, "errors": 0, "failures": 0}
test_perf_analyzer_config (tests.test_perf_analyzer.TestPerfAnalyzerMethods) ... ok
test_run (tests.test_perf_analyzer.TestPerfAnalyzerMethods) ... ok
{"total": 12, "errors": 0, "failures": 0}
test_aggregate (tests.test_record_aggregator.TestRecordAggregatorMethods) ... ok
test_filter_records_default (tests.test_record_aggregator.TestRecordAggregatorMethods) ... ok
test_filter_records_filtered (tests.test_record_aggregator.TestRecordAggregatorMethods) ... ok
test_insert (tests.test_record_aggregator.TestRecordAggregatorMethods) ... ok
test_record_types (tests.test_record_aggregator.TestRecordAggregatorMethods) ... ok
{"total": 17, "errors": 0, "failures": 0}
test_create_client (tests.test_triton_client.TestTritonClientMethods) ... ok
test_load_unload_model (tests.test_triton_client.TestTritonClientMethods) ... ok
test_wait_for_model_ready (tests.test_triton_client.TestTritonClientMethods) ... ok
test_wait_for_server_ready (tests.test_triton_client.TestTritonClientMethods) ... ok
{"total": 21, "errors": 0, "failures": 0}
test_create_server (tests.test_triton_server.TestTritonServerMethods) ... ok
test_server_config (tests.test_triton_server.TestTritonServerMethods) ... ok
test_start_stop_gpus (tests.test_triton_server.TestTritonServerMethods) ... ok
{"total": 24, "errors": 0, "failures": 0}
```

2020-11-20 23:20 UTC, xprotobeast2 requested changes

2020-11-20 23:20 UTC, xprotobeast2 commented on model_analyzer/cli/cli.py
> +            args.triton_metrics_url = 'http://localhost:8002/metrics'
We don't need this anymore. We can go with defaults for now. I deleted this if branch in my end-to-end test PR.

2020-11-20 23:20 UTC, xprotobeast2 commented on model_analyzer/triton/server/server_docker.py
> +    def __init__(self, gpus, model_path, image, config):
Not sure how much this matters but could we place gpus as the last arguments? I think arguments order should be a bit intuitive.

2020-11-20 23:20 UTC, xprotobeast2 commented on model_analyzer/triton/server/server_factory.py
> +    def create_server_docker(gpus, model_path, image, config):
Same here with regards to the order, and in the docstring as well.

2020-11-21 00:50 UTC, dzier approved these changes

2020-11-21 00:57 UTC, xprotobeast2 approved these changes

2020-11-22 18:47 UTC, merged