Update NGC versions post-22.06 release
triton-inference-server/model_analyzer pull request #448
Opened 2022-06-30 18:48 UTC by mc-nv

2022-06-30 20:40 UTC, tgerdesnv requested changes
Can you update docs/quick_start.md as well? There are some values still on 22.05

2022-06-30 21:46 UTC, mc-nv commented
> `docs/quick_start.md`
> `docs/install.md`

@tgerdesnv  I have added changes to the above files

2022-07-01 13:22 UTC, tgerdesnv requested changes

2022-07-01 16:02 UTC, tgerdesnv approved these changes

2022-07-01 19:09 UTC, merged