Added perf analyzer measurement window, and perf output silencing cli…
triton-inference-server/model_analyzer pull request #55
Opened 2020-12-29 01:24 UTC by xprotobeast2

… options

2021-01-05 00:21 UTC, Tabrizian requested changes

2021-01-05 00:21 UTC, Tabrizian commented on model_analyzer/cli/cli.py
> +                 ' <start:end:step> to be used during profiling')
I think `<start:end:step>` can be removed.

2021-01-05 00:21 UTC, Tabrizian commented on model_analyzer/cli/cli.py
> +            help='Time interval between perf_analyzer measurements. perf_analyzer will take '
Mention the unit for the time (e.g. second, milliseconds, etc)

2021-01-05 03:31 UTC, Tabrizian submitted a review, later dismissed

2021-01-06 21:49 UTC, dzier approved these changes

2021-01-09 00:00 UTC, dzier approved these changes

2021-01-09 00:00 UTC, merged